### ISSUE TITLE
Add `itk_image_to_multiscale`

### ISSUE THREAD

**Issue by thewtex** [spatial-image/multiscale-spatial-image#44] opened 2022-05-16 19:39 UTC
This function takes in an `itk.Image`, downscale factors, and optional parameters and returns a MultiscaleSpatialImage.

It consolidates most of this notebook:

  https://github.com/spatial-image/multiscale-spatial-image/blob/main/examples/ConvertITKImage.ipynb

into a single function call.

The optional kwargs should be:

  `anatomical_axes: bool = False` -- whether we consider the axes to be anatomical. If True, set `axis_names` to  `{"x": "right-left", "y": "anterior-posterior", "z": "inferior-superior"}` by default. We also apply the `orient_image_filter` to output `dicom_lps = itk_so_enums.ValidCoordinateOrientations_ITK_COORDINATE_ORIENTATION_RAI` when the `Image` `Direction` is not the identity matrix.
  `axis_names` - Override the axis_names sent to `to_spatial_image`.
  `axis_units` - sent to `to_spatial_image`
  `name` -- name of the image, if `None` (default), check `image.GetObjectName()`, if empty, use `image`.

**Comment by tbirdso** [comment] 2022-05-16 19:41
@thewtex To clarify, are we assuming that `MultiscaleSpatialImage` is always in RAI orientation?

**Comment by thewtex** [comment] 2022-05-16 19:46
@tbirdso at least for now, yes. We could possibly also add support for other axis-aligned orientations in the future. However, the orientation will be explicit with the anatomical_axes names.

**Comment by tbirdso** [comment] 2022-05-16 19:47
@thewtex Got it. Are non-axis-aligned images supported, i.e. with ITK's direction matrix?

**Comment by thewtex** [comment] 2022-05-16 19:51
Since OME-NGFF does not support orientation transformations, we should skip for now. @joshmoore suggested possibly adding an application-specific extension, which we could possibly use until there is orientation transformation support in OME-NGFF.

For now if we encounter a non-axis-aligned image, let's through a warning.

**Comment by tbirdso** [comment] 2022-05-17 18:46
@thewtex It looks like `itk.OrientImageFilter` is wrapped for and applies only to 3D images. How should we handle 2D image orientation if the 2D direction matrix is not the identity matrix?

**Comment by thewtex** [comment] 2022-05-17 19:18
Let's throw an error when `anatomical_axes` is set to `True` and the image is 2D.

**Comment by tbirdso** [comment] 2022-05-17 20:24
Nearing a PR, but running into a memory issue and having trouble pinning down the exact cause. It looks like this happens whenever an ITK filter (i.e. `itk.orient_image_filter`) is called to transform ITK image data before sending it to an xarray, then SpatialImage, then MultiscaleSpatialImage. @thewtex have you seen this before by any chance? Maybe data is being discarded by the filter when it goes out of scope? Using `image.DisconnectPipeline()` has no effect. Do you have suggestions on how to 1) verify that ITK pipeline referencing counting is the cause, and 2) properly disconnect data, possibly in `itk.xarray_from_image`?

```none
test\test_multiscale_spatial_image.py Windows fatal exception: Windows fatal exception: access violation

Current thread 0x00005cd8 (most recent call first):
  File "Windows fatal exception: access violation

Windows fatal exception: access violation

access violation

Windows fatal exception: access violation

Windows fatal exception: access violation

Windows fatal exception: access violationWindows fatal exception: access violation

Windows fatal exception: access violation



Windows fatal exception: access violation

Windows fatal exception: access violationC

:Windows fatal exception: access violation

\Users\tom.birdsong\AppData\Roaming\Python\Python38\site-packages\numpy\core\fromnumeric.py", line 87 in _wrapreduction
  File "C:\Users\tom.birdsong\AppData\Roaming\Python\Python38\site-packages\numpy\core\fromnumeric.py", line 2733 in amax
  File "<__array_function__ internals>", line 5 in amax
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\utils.py", line 40 in apply
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\core.py", line 119 in _execute_task
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\core.py", line 149 in get
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\optimization.py", line 990 in __call__
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\core.py", line 119 in _execute_task
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\local.py", line 221 in execute_task
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\local.py", line 235 in <listcomp>
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\local.py", line 235 in batch_execute_tasks
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\concurrent\futures\thread.py", line 57 in run
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\concurrent\futures\thread.py", line 80 in _worker
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\threading.py", line 870 in run
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\threading.py", line 932 in _bootstrap_inner
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\threading.py", line 890 in _bootstrap

Thread 0x0000422c (most recent call first):
  File "C:\Users\tom.birdsong\AppData\Roaming\Python\Python38\site-packages\numpy\core\fromnumeric.py", line 87 in _wrapreduction
  File "C:\Users\tom.birdsong\AppData\Roaming\Python\Python38\site-packages\numpy\core\fromnumeric.py", line 2733 in amax
  File "<__array_function__ internals>", line 5 in amax
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\utils.py", line 40 in apply
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\core.py", line 119 in _execute_task
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\core.py", line 149 in get
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\optimization.py", line 990 in __call__
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\core.py", line 119 in _execute_task
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\local.py", line 221 in execute_task
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\local.py", line 235 in <listcomp>
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\dask\local.py", line 235 in batch_execute_tasks
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\concurrent\futures\thread.py", line 57 in run
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\concurrent\futures\thread.py", line 80 in _worker
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\threading.py", line 870 in run
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\threading.py", line 932 in _bootstrap_inner
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\threading.py", line 890 in _bootstrap
```

**Comment by thewtex** [comment] 2022-05-17 21:04
A few items to test:

Change:

https://github.com/InsightSoftwareConsortium/ITK/blob/c60f6754c63290bc0bf19280b8ef6249772c669d/Wrapping/Generators/Python/itk/support/xarray.py#L50

`array_view_from_image` -> `array_from_image`.

https://github.com/InsightSoftwareConsortium/ITK/blob/7e5f6c703539c519dd0e3bd24a3bd2fc6d13ea8d/Wrapping/Generators/Python/itk/support/extras.py#L734

`array_view_from_image` -> `array_from_image`.

**Comment by tbirdso** [comment] 2022-05-18 00:47
Thanks @thewtex , it looks like data was being released early due to using a view rather than copy in `itk.xarray_from_image`. I have proposed a change in [https://github.com/InsightSoftwareConsortium/ITK/pull/3438](https://github.com/InsightSoftwareConsortium/ITK/pull/3438) and can duplicate a workaround here while we wait for the next ITK release.

**Closed** 2022-05-19 02:43 UTC
